/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/stage/stage.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Stage(props) {
  const { nodes, materials } = useGLTF("/models/stage/stage.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.table.geometry}
        material={materials.wood}
        scale={[1.408, 1, 1.112]}
      />
      <mesh
        geometry={nodes.newspaper.geometry}
        material={materials["news-paper"]}
      />
      <mesh
        geometry={nodes["glass-bowl"].geometry}
        material={materials["glass-bowl-material"]}
      />
      <mesh
        geometry={nodes.spoon.geometry}
        material={materials["spoon-material"]}
      />
      <mesh
        geometry={nodes.cup001.geometry}
        material={materials["coffee-cup"]}
      />
      <mesh
        geometry={nodes.saucer001.geometry}
        material={materials["coffee-cup"]}
      />
      <mesh
        geometry={nodes["coffee-liquid"].geometry}
        material={materials["coffee-liquid"]}
      />
    </group>
  );
}

useGLTF.preload("/models/stage/stage.glb");
