/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/stage/stage.glb 
*/

import React from "react";
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei";

export default function Stage(props) {
  const { nodes, materials } = useGLTF("/models/stage/stage.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.table.geometry}
        material={materials.wood}
        scale={[1.408, 1, 1.112]}
      />
      <mesh
        geometry={nodes.newspaper.geometry}
        material={materials["news-paper"]}
      />
      <mesh
        geometry={nodes["glass-bowl"].geometry}
        // material={materials["glass-bowl-material"]}
      >
        <MeshTransmissionMaterial
          backside
          samples={6} // refraction samples, default: 6
          transmission={1}
          thickness={0.9}
          chromaticAberration={0.05}
          anisotropy={0.9} // the structural property of non-uniformity in different directions, default: 0.1
          distortion={0.2} // default: 0
          distortionScale={0.6}
          temporalDistortion={0.1} // speed of movement, default: 0.0
          iridescence={1} // certain surfaces that appear gradually to change colour
          iridescenceIOR={1}
          iridescenceThicknessRange={[100, 400]}
        />
      </mesh>
      <mesh
        geometry={nodes.spoon.geometry}
        material={materials["spoon-material"]}
      />
      <mesh
        geometry={nodes.cup001.geometry}
        material={materials["coffee-cup"]}
      />
      <mesh
        geometry={nodes.saucer001.geometry}
        material={materials["coffee-cup"]}
      />
      <mesh
        geometry={nodes["coffee-liquid"].geometry}
        material={materials["coffee-liquid"]}
      />
    </group>
  );
}

useGLTF.preload("/models/stage/stage.glb");
